#!/bin/bash
################################################################################
# About:
# Script to setup server with apache webserver and setup script to record 
# sessions and automatically update webpage available under
# (http://<ipaddress>/session)
#-------------------------------------------------------------------------------
# Author:
#           jayanatl@gmail.com
# Modifications:
#           jayanatl@gmail.com                  Initial copy        (2018-04-25)
################################################################################
# Variables
web_loc="sessions"
# Check for normal user
if [ ${EUID} -eq 0 ]; then
    echo "Error: Run this command as a normal user, with sudo access"
    exit 127
fi

# Install and configure httpd
sudo yum -y install httpd
sudo mkdir -p /var/www/html/${web_loc}/.data

# Download necessary code and configure
sudo cp -r view/* /var/www/html/${web_loc}/
sudo cp index.html /var/www/html/${web_loc}/index.html

mkdir -p ~/workshop/{bin,sessions}
grep 'PATH=$PATH:~/workshop/bin' ~/.bashrc || echo 'export PATH=$PATH:~/workshop/bin' >> ~/.bashrc
export PATH=$PATH:~/workshop/bin
cp jsonify start_recording ~/workshop/bin/
chmod u+x ~/workshop/bin/{jsonify,start_recording}

# Start apache server
sudo systemctl enable httpd
sudo systemctl start httpd
echo "Connect to following urls to access sessions:"

for ipaddr in `ip a s|grep -w inet|awk '{print $2}'|cut -d'/' -f 1`; do
    echo "    http://${ipaddr}/${web_loc}"
done
