#!/bin/bash
################################################################################
# About:
# Script to start recording and make it available under
# (http://<ipaddress>/session)
#-------------------------------------------------------------------------------
# Author:
#           jayanatl@gmail.com
# Modifications:
#           jayanatl@gmail.com                  Initial copy        (2018-04-25)
################################################################################
# Variables
web_loc="sessions"
web_loc="/var/www/html/"${web_loc}
term_cols="160"
term_lines="48"

# Sanity check
which jsonify || { echo "Error: Unable to locate jsonify"; exit 127; }

# set terminal properties
pushd ~/workshop/sessions || { echo "Error: Unable to switch to workshop directory"; exit 127; }
while [[ `tput cols` != ${term_cols} || `tput lines` != ${term_lines} ]]; do
    read -p "Resize terminal to ${term_cols}x${term_lines}. Press Enter to continue..."
    watch "tput cols; tput lines"
done

# Start script session
read -p "Enter name of the session: " name
echo "Name read: ${name}"
[ -z ${web_loc}/.data/${name} ] && { echo "Error: Session name cannot be empty"; exit 127; }
[ -f ${web_loc}/.data/${name} ] && { echo "Error: File exist with same name"; exit 127; }
script -t${name}.t ${name}.s

# Process session recording
jsonify ${name}.s ${name}.t > ${name}
sudo cp ${name} ${web_loc}/.data/
[ -f ${web_loc}/.data/${name} ] && rm -f ${name}*

# Publish session recording
cp ${web_loc}/index.html .
touch index.html
echo "<br>Session: <a href=\"view.html?${name}\">${name}</a>"  >> index.html
sudo cp index.html ${web_loc}/index.html
popd
